# maintainer: Adam Mollenkopf (@amollenkopf)
FROM javidelgadillo/mesosphere-spark_2.11
ADD ./target/scala-2.10/spatiotemporal-esri-analytic-task-assembly-1.0.jar /jars/spatiotemporal-esri-analytic-task-assembly-1.0.jar
